apiVersion: tronador.stakater.com/v1alpha2
kind: Environment
metadata:
  name: main-review-ui-2
spec:
  application:
    gitRepository:
      gitImplementation: go-git
      interval: 1m0s
      ref:
        branch: main
      timeout: 20s
      url: 'https://github.com/stakater-lab/stakater-nordmart-review-ui'
    release:
      chart:
        spec:
          chart: deploy/
          reconcileStrategy: ChartVersion
          sourceRef:
            kind: GitRepository
            name: dte-main
          version: '*'
      interval: 1m0s
      releaseName: main
      values:
        application:
          deployment:
            image:
              repository: >-
                nexus-docker-stakater-nexus.apps.binero-test.8sdzwd1l.kubeapp.cloud/stakater-nordmart-review-ui
              tag: v1.0.1
  namespaceLabels:
    label: value
    owner: stakater
    stakater.com/tenant: alpha
